name: Builder

on:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential patch gcc-14-arm-linux-gnueabi g++-14-arm-linux-gnueabi g++-14-aarch64-linux-gnu gcc-14-aarch64-linux-gnu cmake bc flex bison 7zip kmod bash cpio binutils tar git wget dpkg libssl-dev python3 python-is-python3

      - name: Build kernel
        run: sudo sh box_build.sh

      - name: Upload deb packages
        uses: actions/upload-artifact@v4
        with:
          name: box_${{ matrix.version }}
          path: ${{ github.workspace }}/*.deb
