name: Builder

on:
  workflow_dispatch:

jobs:
  box:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential libc6-dev patch gcc-14-arm-linux-gnueabi gcc-14-aarch64-linux-gnu cmake bash git dpkg python3 python-is-python3

      - name: Build Box86 and Box64
        run: sudo sh box_build.sh

      - name: Upload deb packages
        uses: actions/upload-artifact@v4
        with:
          name: box_x86_64-armhf_arm64
          path: ${{ github.workspace }}/*.deb
