name: Builder

on:
  workflow_dispatch:

jobs:
  box:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install patch gcc-14-arm-linux-gnueabihf gcc-14-aarch64-linux-gnu cmake git python3 python-is-python3

      - name: Build Box86 and Box64
        run: sudo sh box_build.sh ${{ github.workspace }}

      - name: Upload deb packages
        uses: actions/upload-artifact@v4
        with:
          name: box96
          path: ${{ github.workspace }}/*.deb
